### ISSUE TITLE
Support Anonymized debug output

### ISSUE THREAD

**Issue by sjourdan** [snyk/driftctl#1006]
**Description**

When we need users help, we ask for debug logs (`LOG_LEVEL=debug`).

Often, nothing identifiable is outputted - random IDs etc. Nothing really critical. 

But we repeatedly met users with privacy issues because identifiable names or words could give private information or customer names etc. The classic issue. 

We may want to find a solution radically remove anything identifiable. An idea is something around the lines of 

- for each resource name, 
- hash all resource names
- and all its occurrences

In this case, all the resource names like 

```hcl
resource "aws_route53_zone" "redhat" {
  name = "redhat.com"
}
```

could become in the output 

```hcl
resource "aws_route53_zone" "7D3B5C83009FADF734C06EEECD7FBE256C69F71C8BA0429E4D7AD5F54B2E4097" {
  name = "7D3B5C83009FADF734C06EEECD7FBE256C69F71C8BA0429E4D7AD5F54B2E4097.com"
}
```

Just an idea.

**Comment by sjourdan** [comment]
Let's transform this issue into an RFC

**Comment by eliecharra** [comment]
@sjourdan Can we close that one ?

**Comment by sjourdan** [comment]
the need is expressed in the RFC so yes. 

That said, this exact need should probably be extracted from this RFC to be scoped more precisely.
