### ISSUE TITLE
Default `aws_api_gateway_account` should be ignored 

### ISSUE THREAD

**Issue by wbeuil** [snyk/driftctl#1217]
**Description**

We all have an `aws_api_gateway_account` resource inside each region of AWS that will by default output as unmanaged. We should ignore this one unless you manage it by Terraform.

**How to reproduce**

Simply test with the most recent version of driftctl `driftctl scan`, you should have one unmanaged`aws_api_gateway_account` resource.

**Possible Solution**

New middleware to ignore the default resource.

**Comment by sundowndev** [comment]
Released in [v0.19.0](https://github.com/snyk/driftctl/releases/tag/v0.19.0).
