### ISSUE TITLE
aws_apigatewayv2_domain_name

### ISSUE THREAD

**Issue by sundowndev** [snyk/driftctl#1257]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_domain_name

**Comment by wbeuil** [comment]
To keep an explanation of why, as a user, you will only see `aws_api_gateway_domain_name` (v1) resources as unmanaged and never `aws_apigatewayv2_domain_name` (v2), I invite you to check the PR I wrote [here](https://github.com/snyk/driftctl/pull/1320#issue-1102006740).

TL;DR, both (v1|v2) AWS SDK endpoints to list domain names return v1 AND v2 resources with no way to find which one is which. We decided to find managed resources by looping over matched remote and state ones, and leave only v1 unmanaged ones in the output.
