### ISSUE TITLE
Support multiple states and projects for GCP

### ISSUE THREAD

**Issue by bgdanix** [snyk/driftctl#1273]
**Description**
Currently driftctl requires the project where to perform the scan on in GCP. A more robust approach would be the following:

1. Support multiple state files
2. Concatenate `resources` lists from the files into one
3. Extract the unique project IDs from the resource name or resource project field of the concatenated state, thus not having a need for specifying the target project(s) to scan
4. Search the assets from each of the discovered project(s)
5. Perform the diff and the next steps

**Example**
Before:

```bash
GOOGLE_APPLICATION_CREDENTIALS=your-creds.json\
  CLOUDSDK_CORE_PROJECT=my-project\
  driftctl scan --to gcp+tf --from tfstate+gs://
```

After:
```bash
GOOGLE_APPLICATION_CREDENTIALS=your-creds.json\
  driftctl scan --to gcp+tf --from tfstate+gs://
```

**Comment by eliecharra** [comment]
I'm closing this one in flavor of #1284 #1286
