### ISSUE TITLE
Azure: error scanning resource type azurerm_storage_account

### ISSUE THREAD

**Issue by nie-kita2** [snyk/driftctl#1307]
**Description**

I get the following error message scanning Azure Terraform state file:
```
error scanning resource type azurerm_storage_account: unmarshalling type *armstorage.StorageAccountListResult: parsing time "NULL" as ""2006-01-02T15:04:05.999999999"": cannot parse "NULL" as """
```

**Environment**
 - OS: Ubuntu
 - driftctl version: 0.18.0
 - terraform version: 1.1.2
 - terraform providers versions: azure@2.90.0

**How to reproduce**

```
terraform state pull > $TMP_STATE
driftctl scan --to azure+tf --from tfstate://$TMP_STATE
```

**Possible Solution**

Searching around, I got the following similar article: https://issueexplorer.com/issue/Azure/azure-sdk-for-go/16135
As I see, there is azcore v0.19.0 currently being used. Perhaps, there is an upgrade necessary.

**Comment by sundowndev** [comment]
Hi @nie-kita2, thanks for noticing about this bug!

I couldn't reproduce it locally but I managed to upgrade all Azure packages at once (we've been struggling with their new modules for months). I pushed a PR for it and I'll ping you when it gets released.

**Comment by sundowndev** [comment]
Azure dependencies were updated in [v0.18.5](https://github.com/snyk/driftctl/releases/tag/v0.18.5).
