### ISSUE TITLE
Glob pattern matching within a GCS backend

### ISSUE THREAD

**Issue by sundowndev** [snyk/driftctl#1330]
**Description**

For now, only filesystem and S3 are compatible with glob patterns. Just like we did in #316, we should be able to use glob patterns with the GCS backend, which is currently not possible.

**Example**

What we're currently able to do : 

```
$ driftctl scan -f 'tfstate+gs://my-bucket/terraform/state/default.tfstate' --to gcp+tf
```

What we should be able to do as well : 

```
$ driftctl scan -f tfstate+gcs://my-bucket/terraform/**/*.tfstate --to gcp+tf
```

**Implementation**

We should create a new *GS* enumerator that works pretty much the same as the S3 enumerator does. Found this example online to list content of a bucket using the Go SDK : 

```go
func main() {
	ctx := context.Background()

	client, err := storage.NewClient(ctx)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}
	defer client.Close()

	// Sets the name for the new bucket.
	bucketName := "test-bucket"

	// Creates a Bucket instance.
	bucket := client.Bucket(bucketName)

	it := bucket.Objects(ctx, &storage.Query{})
	for {
		attrs, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			panic(err)
		}
		if attrs.Size == 0 {
			continue
		}
		fmt.Println(filepath.Join(attrs.Bucket, attrs.Name))
	}
}
```

**References**
- https://globster.xyz/?q=**%2F*.tfstate&f=%2Froute53%2Fterraform.tf%2C%2Froute53%2Fterraform.tfstate%2C%2Fs3%2Fterraform.tf%2C%2Fs3%2Fterraform.tfstate%2C%2Fec2%2Fterraform.tf%2C%2Fec2%2Fsubfolder%2Fterraform.tf%2C%2Fec2%2Fsubfolder%2Fterraform.tfstate

**Comment by bschaatsbergen** [comment]
Happy to pick this up, this is currently a gamebreaker for most Google Cloud users.
