### ISSUE TITLE
html output on stdout shows progress and all the non html output

### ISSUE THREAD

**Issue by moadibfr** [snyk/driftctl#1358]
**Description**
Output to stdout is not supposed to display progress and all the others warning/info (like provider version scan duration and everything).
This does work with `json://stdout`but does not with `html://stdout` thus you cannot pipe the output to a html file

**Environment**
 - OS: darwin
 - driftctl version: v0.19.0

**How to reproduce**
run a scan with ` scan --output html://stdout`. The output will show progress and other non html output.

**Comment by patch-the-dog** [comment]
This issue has been referenced in the latest release v0.21.0.
