### ISSUE TITLE
RepositoryPolicyNotFoundException

### ISSUE THREAD

**Issue by stantruera** [snyk/driftctl#1549]
**Description**
```bash
# driftctl scan
Scanned states (1)
RepositoryPolicyNotFoundException: Repository policy does not exist for the repository with name 'daily/all' in the registry with id '***hidden***'
```

**Environment**
 - OS: macOS
 - driftctl version: 0.34.0
 - terraform version: v1.2.3
 - terraform providers versions:
+ provider registry.terraform.io/hashicorp/aws v4.19.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/random v3.3.1
+ provider registry.terraform.io/hashicorp/tls v3.4.0

**How to reproduce**
have no idea, I just downloaded it and ran `driftctl scan`

**Possible Solution**
please tell how to debug

**Comment by eliecharra** [comment]
I reproduced it locally, it was introduced recently because of that PR [#1425 ](https://github.com/snyk/driftctl/pull/1494)

Fix coming very soon
