### ISSUE TITLE
CDKTF support?

### ISSUE THREAD

**Issue by omerlh** [snyk/driftctl#1564]
**Description**
Hey, does driftctl supports CDKTF?

I am testing it with a very simple application:

```
import { Construct } from "constructs";
import { App, TerraformStack, TerraformOutput } from "cdktf";
import { AwsProvider, ec2 } from "@cdktf/provider-aws";

class MyStack extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    new AwsProvider(this, "AWS", {
      region: "us-east-1",
      profile: "<>"
    });

    const instance = new ec2.Instance(this, "compute", {
      ami: "ami-01456a894f71116f2",
      instanceType: "t2.micro",
    });

    new TerraformOutput(this, "public_ip", {
      value: instance.publicIp,
    });
  }
}

const app = new App();
new MyStack(app, "root");
app.synth();

```

And while this is deployed correctly, when running cdktf on the generated TF files I am getting very weird error:

```
LOG_LEVEL=debug AWS_PROFILE=<> driftctl scan
DEBU[0000] Build info isRelease=true isSnyk=false isUsageReportingEnabled=true version=v0.35.1
DEBU[0000] Found provider version in terraform lock file provider=aws+tf version=4.22.0
DEBU[0000] New provider library created
DEBU[0001] Found existing provider path=/Users/<>/.driftctl/plugins/darwin_arm64/terraform-provider-aws_v4.22.0_x5
DEBU[0001] Starting gRPC client alias=
Invalid AWS Region: 
```

**Environment**
 - OS: macos
 - driftctl version: v0.35.1
 - terraform version: v1.2.5
 - terraform providers versions: 

**How to reproduce**
Just generate new empty cdktf project, like mentioned [here](https://learn.hashicorp.com/tutorials/terraform/cdktf-build?in=terraform/1-0)

**Comment by moadibfr** [comment]
hey @omerlh thanks for the report !
I'm not sure how CDKTF works so I don't really know if we support everything.
But from the logs you gave I think you are missing some credential/configuration for AWS. 
If you update your driftctl version you should have a more explicit error.
You could try checking if your profile is complete (https://docs.driftctl.com/0.35.0/providers/aws/authentication) and check if the scan work correctly.

Btw if you do that we would really like to know if you succeeded using driftctl for your use-case !

**Comment by craigfurman** [comment]
Closing due to silence, please feel free to re-open if you're still having issues.
