### ISSUE TITLE
driftctl does not respect providers

### ISSUE THREAD

**Issue by marafa-sugarcrm** [snyk/driftctl#1592]
**Description**

the docs says the minimum command needed is `driftctl scan` however when i attempt to do that, i get 
```
Could not find a way to authenticate on AWS!
Please refer to AWS documentation: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html
```
i have verified that running `terraform state` works in the same directory as i ran `driftctl scan`

i also get the same result when setting tfstate to the s3 bucket . 

now here is the thing. the bucket is in a different account and so when i run `aws --profile account_resources s3 ls $path2state` i get a similar error: 
```
An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Environment**
 - OS: mac
 - driftctl version: v0.38.1
 - terraform version: Terraform v1.3.2
 - terraform providers versions:  
 - + provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.74.3
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/tls v4.0.1

**How to reproduce**

```
terraform {
  backend "s3" {
    bucket  = "tf_bucket"
    key     = "path/2/terraform.tfstate"
    region  = "us-west-2"
    encrypt = true
    profile = "account_bucket"
  }
}

provider "aws" {
  profile = "account_resources"
  region  = var.region
}
```

**Possible Solution**

**Additional context**

**Comment by wbeuil** [comment]
Hey @marafa-sugarcrm 👋🏻 by looking at your terraform I can see that you're using too different AWS profile. One for init your backend `accout_bucket` and one for the provider you want to use `account_resources`. So you explicitly said to terraform which profile to use, you're gonna need to do the same for driftctl. We're not looking at you hcl code so we can't infer your AWS profile.

A simple `AWS_PROFILE=account_resources DCTL_S3_PROFILE=account_bucket DCTL_S3_REGION=us-west-2 driftctl scan --from tfstate+s3://tf_bucket/path/2/terraform.tfstate` should work if the region of your AWS profile is the same as the `var.region` you declared in your terraform.

Don't hesitate to look at our docs at [docs.driftctl.com](https://docs.driftctl.com/0.38.0/providers/aws/authentication) if you have a problem running `driftctl`.

**Comment by marafa-sugarcrm** [comment]
thank you
things are working now!
