### ISSUE TITLE
aws provider 4.38.0 html output error

### ISSUE THREAD

**Issue by tinder-tder** [snyk/driftctl#1597]
**Description**

when running a scan with --deep and the latest aws provider version we are seeing an error on html output (json output is fine)

```
ERRO[0204] Error writing to output html://output.html: template: main:144:67: executing "main" at <jsonDiff $diff.Changelog>: error calling jsonDiff: runtime error: invalid memory address or nil pointer dereference
Scan duration: 3m23s
Provider version used to scan: 4.38.0. Use --tf-provider-version to use another version.
```
**Environment**
 - OS: OSX
 - driftctl version: 0.38.1
 - terraform providers versions: aws@4.38.0

**How to reproduce**
driftctl scan --from "tfstate+s3://${BUCKET}/**/*.tfstate" --output json://output.json --output html://output.html --deep --tf-provider-version 4.38.0

**Comment by wbeuil** [comment]
Hey @tinder-tder, I didn't succeed at reproducing the bug with the command you gave.

Maybe there's a bug under neath. Could you try to reproduce with a fresh simple repo?

**Comment by tinder-tder** [comment]
@wbeuil will get back to thi after the holiday this week

**Comment by tinder-tder** [comment]
@wbeuil  i tested on the latest 4.41 provider on the same account and it errored out the same.  I reran against another account and it finished properly for both json and html output
```
1677 ~/git/terragrunt % ./dc.sh 
Scanned states (96)      
Scan duration: 11m50s  
Provider version used to scan: 4.41.0. Use --tf-provider-version to use another version.
1678 ~/git/terragrunt % 
```
So it must be a specific resource or the scale that is causing it in the original test account.  I will reopen when i find something more concrete.
