### ISSUE TITLE
Missing aws_lb_listener resource false positives (due to caching bug)

### ISSUE THREAD

**Issue by martin-vanta** [snyk/driftctl#1598]
**Description**

I think I've found a bug with caching load balancer listeners that is causing false positives for missing `aws_lb_listener` resources.

Specifically, a static cache key is used when it should be dependent on the load balancer ARN. As a result, if you have multiple load balancers, then this will return the same set of listeners as the first LB.

See: https://github.com/snyk/driftctl/blob/main/enumeration/remote/aws/repository/elbv2_repository.go#L47-L48

I believe this behaviour then manifests as (1) flagging listeners on AWS as missing, and (2) flagging the incorrectly duplicated listeners as not covered by IaC.

For example, with debug level logs, we can see 5 found LBs followed by 5 of the exact same listeners. Coincidentally or not the duped listeners correspond to the first found LB.

```
DEBU[0013] Found cloud resource id=arn:aws:elasticloadbalancing:us-east-1:11111:loadbalancer/net/api-network/3ede8ffa0e1531b2 type=aws_lb
DEBU[0013] Found cloud resource id=arn:aws:elasticloadbalancing:us-east-1:11111:loadbalancer/net/auth-network/6e694f54186c2327 type=aws_lb
DEBU[0013] Found cloud resource id=arn:aws:elasticloadbalancing:us-east-1:11111:loadbalancer/app/internal/5979cf6b8256747f type=aws_lb
DEBU[0013] Found cloud resource id=arn:aws:elasticloadbalancing:us-east-1:11111:loadbalancer/app/public/8cb69746e8f4a7dc type=aws_lb
DEBU[0013] Found cloud resource id=arn:aws:elasticloadbalancing:us-east-1:11111:loadbalancer/app/osquery/364499750f0d3c88 type=aws_lb
DEBU[0013] Found cloud resource id=arn:aws:elasticloadbalancing:us-east-1:11111:listener/net/api-network/3ede8ffa0e1531b2/305a5ca61746bfe0 type=aws_lb_listener
DEBU[0013] Found cloud resource id=arn:aws:elasticloadbalancing:us-east-1:11111:listener/net/api-network/3ede8ffa0e1531b2/305a5ca61746bfe0 type=aws_lb_listener
DEBU[0013] Found cloud resource id=arn:aws:elasticloadbalancing:us-east-1:11111:listener/net/api-network/3ede8ffa0e1531b2/305a5ca61746bfe0 type=aws_lb_listener
DEBU[0013] Found cloud resource id=arn:aws:elasticloadbalancing:us-east-1:11111:listener/net/api-network/3ede8ffa0e1531b2/305a5ca61746bfe0 type=aws_lb_listener
DEBU[0013] Found cloud resource id=arn:aws:elasticloadbalancing:us-east-1:11111:listener/net/api-network/3ede8ffa0e1531b2/305a5ca61746bfe0 type=aws_lb_listener
```

The end output of scan is then missing listeners for the other LBs (i.e. not the non `api-network` LBs), and the 4 duped listeners are also marked as not being covered by IaC.

```
Found missing resources:
  - arn:aws:elasticloadbalancing:us-east-1:11111:listener/app/internal/5979cf6b8256747f/65bf2c5c2c534db1 (aws_lb_listener)
  - arn:aws:elasticloadbalancing:us-east-1:11111:listener/app/osquery/364499750f0d3c88/146a5b7983e8b30c (aws_lb_listener)
  - arn:aws:elasticloadbalancing:us-east-1:11111:listener/app/public/8cb69746e8f4a7dc/0d2fef931dae808c (aws_lb_listener)
  - arn:aws:elasticloadbalancing:us-east-1:11111:listener/app/public/8cb69746e8f4a7dc/93b7b0f067aae11b (aws_lb_listener.http-to-https)
  - arn:aws:elasticloadbalancing:us-east-1:11111:listener/net/auth-network/6e694f54186c2327/47ee80d887bff3f5 (module.auth-service.aws_lb_listener.service)
Found resources not covered by IaC:
  aws_lb_listener:
    - arn:aws:elasticloadbalancing:us-east-1:11111:listener/net/api-network/3ede8ffa0e1531b2/305a5ca61746bfe0
    - arn:aws:elasticloadbalancing:us-east-1:11111:listener/net/api-network/3ede8ffa0e1531b2/305a5ca61746bfe0
    - arn:aws:elasticloadbalancing:us-east-1:11111:listener/net/api-network/3ede8ffa0e1531b2/305a5ca61746bfe0
    - arn:aws:elasticloadbalancing:us-east-1:11111:listener/net/api-network/3ede8ffa0e1531b2/305a5ca61746bfe0
Found 549 resource(s)
 - 93% coverage
 - 513 resource(s) managed by Terraform
 - 30 resource(s) not managed by Terraform
 - 5 resource(s) found in a Terraform state but missing on the cloud provider
```

**Environment**
 - OS: macOS
 - driftctl version: `v0.38.1`
 - terraform version: `v1.1.6`
 - terraform providers versions: aws@4.23.0

**How to reproduce**

**Possible Solution**

If folks agree, I can put up a simple fix to include the LB ARN in the cache key.

**Additional context**

**Comment by wbeuil** [comment]
Hey @martin-vanta 👋🏻 

It seems you're absolutely right, the cache key should be linked to the ARN of the LB we want to find listeners for.

If you feel contributing to driftctl, please do so. For the fix, please look at other repositories like [this one](https://github.com/snyk/driftctl/blob/main/enumeration/remote/aws/repository/sqs_repository.go#L30-L34) where the cache key is also based on the argument.

**Comment by patch-the-dog** [comment]
This issue has been referenced in the [v0.38.2 release](https://github.com/snyk/driftctl/releases/tag/v0.38.2).
