### ISSUE TITLE
Driftctl ThrottlingException: Rate exceeded on AWS

### ISSUE THREAD

**Issue by sanazba** [snyk/driftctl#1629]
I'm  facing a rate limit error from AWS,
ThrottlingException: Rate exceeded status code: 400
Is there any way to throttle the requests from Driftctl?

**Comment by jangraefen** [comment]
Maybe have a look at this issue: #1344 
The suggestion at the bottom actually proved to be a valid workaround for me 🙂.

**Comment by sanazba** [comment]
Thanks for the help, Im gonna close this issue.
