### ISSUE TITLE
Add support for Azure blob state backend

### ISSUE THREAD

**Issue by sundowndev** [snyk/driftctl#352]
**Description**

As stated in #270, user may want to fetch the Terraform state from a remote storage backend such as Azure blob, in order to be able to scan remote state from them.

**Example**

```
$ driftctl scan --from tfstate+azurerm://my-blob/path/to/state.tfstate
```

**Comment by sjourdan** [comment]
we definitely want this done at some point

**Comment by patch-the-dog** [comment]
This issue has been referenced in the latest release v0.21.0.
