### ISSUE TITLE
Support aws_elb resource

### ISSUE THREAD

**Issue by sjourdan** [snyk/driftctl#919]
**Description**

As a terraform & driftctl user
I want to detect AWS ELB drifts 
So that I can improve my coverage or security

**Example**

**Comment by sjourdan** [comment]
currently blocked by EKS support investigation

**Comment by patch-the-dog** [comment]
This issue has been referenced in the [v0.28.0 release](https://github.com/snyk/driftctl/releases/tag/v0.28.0).
