### ISSUE TITLE
Update to go 1.17

### ISSUE THREAD

**Issue by eliecharra** [snyk/driftctl#943]
**Description**

In order to get smaller binaries, we should upgrade to go 1.17.

ping @moadibfr 😉 check the quote below

> go mod download
>> When go mod download is invoked without arguments, it will no longer save sums for downloaded module content to go.sum. It may still make changes to go.mod and go.sum needed to load the build list. This is the same as the behavior in Go 1.15. To save sums for all modules, use go mod download all.

Things to check:
- [x] We should check if it will work with homebrew

References:
- https://twitter.com/kelseyhightower/status/1427400588900241410
- https://golang.org/doc/go1.17

**Comment by craigfurman** [comment]
What's the homebrew concern?

**Comment by moadibfr** [comment]
> What's the homebrew concern?

not sure but it might have been about the availability of the go version I think there was some delay with new go version in homebrew at some point ?

**Comment by craigfurman** [comment]
Don't we ship a compiled binary to homebrew though, without a brew-dependency on the go package?

**Comment by eliecharra** [comment]
> Don't we ship a compiled binary to homebrew though, without a brew-dependency on the go package?

Nope, homebrew is building binary on their side. So we should be sure that we can build with go 1.17 on homebrew.

**Comment by craigfurman** [comment]
oh, today I learned, thanks! I should have read the packaging properly before making that assumption.

**Comment by eliecharra** [comment]
Like many pkg managers, they need to take responsibilities on binary they ship to the world.
Allowing people to send their own binary can lead to potential malicious binaries injected in the repo if you know what I mean.
For example if the snyk supply chain is compromised, brew binaries will not be affected.

I think this is subject to debate, and this is more a question about who you want to trust.
Personally I prefer choose explicitly which GPG key I trust in a granular way than trusting a whole pkg manager that build its binaries in a blackbox.
I like trusting explicitly driftctl release key and then check binary signatures on my device.

**Comment by sundowndev** [comment]
From what I understand, the [`go` formula we use](https://github.com/Homebrew/homebrew-core/blob/master/Formula/go.rb) to build the binary in Homebrew uses Go 1.17. I guess we can safely upgrade to 1.17 then.
