### ISSUE TITLE
Support AWS API Gateway

### ISSUE THREAD

**Issue by sjourdan** [snyk/driftctl#960]
**Description**

This service is highly split into small resources, let group them here first. 

- [x] #1110
- [x] #1111
- [x] #1112
- [x] #1113
- [x] #1114
- [x] #1125
- [x] #1115
- [ ] aws_api_gateway_deployment (dropped)
- [x] #1157
- [x] #1179
- [x] #1199
- [x] #1140
- [x] #1164
- [x] #1170
- [x] #1150
- [x] #1133
- [x] #1117
- [x] #1116
- [x] #1109

**Example**

TF doc: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_resource

**Comment by eliecharra** [comment]
@sjourdan How to you want to handle testing for this one ? We merged `rest_api` resource, should I put this issue in review ?

**Comment by wbeuil** [comment]
All v1 resources merged
