### ISSUE TITLE
Support AWS API Gateway v2 (WS/HTTP)

### ISSUE THREAD

**Issue by sjourdan** [snyk/driftctl#961]
**Description**

Support for AWS API Gateway v2 is highly split into very small resources. Let's group them here for now. 

- [x] #1222
- [x] #1275
- [x] #1247
- [x] #1310
- [x] #1257
- [x] #1258
- [x] #1271
- [x] #1262
- [x] #1249
- [x] #1272
- [x] #1261
- [x] #1223

**Example**

TF doc: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_api

**Comment by gitkit13** [comment]
https://github.com/naist-nlp/structlens
