### ISSUE TITLE
Display "out of sync" drifts only on deep-mode

### ISSUE THREAD

**Issue by wbeuil** [snyk/driftctl#964]
**Description**
For the non-deep mode, which is the default `driftctl scan` command, we display every time all the information about "unmanaged", "deleted", "drifted", "managed" resources, and the coverage. 

It's quite unhelpful here to display the "drifted" resources since it would be ALL THE TIME equal to 0.

**Example**
```
Found 14 resource(s)
 - 21% coverage
 - 3 resource(s) managed by terraform
     - 0/3 resource(s) out of sync with Terraform state <- Not relevant in non-deep mode
 - 10 resource(s) not managed by Terraform
 - 1 resource(s) found in a Terraform state but missing on the cloud provider
```

**Comment by eliecharra** [comment]
Nice catch, this is very relevant 👍🏻 

Maybe it can be a good first issue ?

**Comment by wbeuil** [comment]
> Nice catch, this is very relevant 👍🏻
> 
> Maybe it can be a good first issue ?

Absolutely!
