### ISSUE TITLE
Support GCE google_compute_instance_group_manager (TF)

### ISSUE THREAD

**Issue by sjourdan** [snyk/driftctl#998]
**Description**

Add GCE support for `google_compute_instance_group_manager` (TF)

**Sources**

* [Terraform Resource Documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group_manager)
* [GCP Resource Documentation](https://cloud.google.com/asset-inventory/docs/supported-asset-types#supported_resource_types)

**Comment by patch-the-dog** [comment]
This issue has been referenced in the [v0.26.0 release](https://github.com/snyk/driftctl/releases/tag/v0.26.0).
